apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  labels:
    name: vote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: vote-app
  template:
    metadata:
      name: vote-app
      labels:
        name: vote-app
    spec:
      containers:
        - name: vote-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
