apiVersion: v1
kind: Template
metadata:
  name: playground-heiko-template
objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: playground-heiko-pod-v${VERSION}
      labels:
        app: playground-heiko-pod-v${VERSION}
        type: playground
    spec:
      containers:
        - name: nginx-container
          image: nginxinc/nginx-unprivileged:alpine
  - apiVersion: v1
    kind: Service
    metadata:
      name: playground-heiko-service-v${VERSION}
    spec:
      selector:
        app: playground-heiko-pod-v${VERSION}
      ports:
        - port: 8080
  - apiVersion: v1
    kind: Route
    metadata:
      name: playground-heiko-route-v${VERSION}
    spec:
      host: playground-heiko-${VERSION}.apps.eu.idealo.com
      to:
        kind: Service
        name: playground-heiko-service-v${VERSION}
parameters:
  - name: VERSION
    displayName: version number
    description: version to deploy
    required: true
