info:
	kubectl get pods
	kubectl get replicationcontroller
	kubectl get replicaset

create-pod:
	kubectl create -f pod-definition.yml

create-rc:
	kubectl create -f rc-definition.yml

create-replicaset:
	kubectl create -f replicaset-definition.yml

clean-pod:
	kubectl delete pod myapp-pod

clean-rc:
	kubectl delete replicationcontroller myapp-rc

clean-replicaset:
	kubectl delete replicaset myapp-replicaset
