info:
	kubectl get pods
	kubectl get replicationcontroller

create-pod:
	kubectl create -f pod-definition.yml

create-rc:
	kubectl create -f rc-definition.yml

clean-pod:
	kubectl delete pod myapp-pod

clean-rc:
	kubectl delete replicationcontroller myapp-rc
